version: '3.8' # Specifica la versione di docker-compose

services:
  # Definiamo il nostro primo "servizio"
  web:
    # Usiamo l'immagine ufficiale di Nginx
    # "alpine" è una versione super-leggera di Linux
    image: nginx:alpine 

    container_name: frontend

    # Mappatura delle porte:
    # Collega la porta 8080 del TUO PC (Windows)
    # alla porta 80 DENTRO il container (dove Nginx ascolta)
    ports:
      - "8080:80" 

    # Mappatura dei volumi (la parte più importante):
    # Collega la nostra cartella locale "./src"
    # alla cartella "/usr/share/nginx/html" DENTRO il container
    # (che è dove Nginx cerca i file .html)
    volumes:
      - ./src:/usr/share/nginx/html:ro 

    # ":ro" significa "read-only" (sola lettura).
    # È una buona pratica: il container non deve modificare
    # il nostro codice sorgente.